/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paquete;

import java.awt.List;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author dam2
 */
public class frame1 extends javax.swing.JFrame {

    /**
     * Creates new form frame1
     */

    public frame1() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        campoApellidos = new javax.swing.JTextField();
        botonGuardar = new javax.swing.JButton();
        botonHombre = new javax.swing.JRadioButton();
        botonMujer = new javax.swing.JRadioButton();
        checkCine = new javax.swing.JCheckBox();
        checkViajes = new javax.swing.JCheckBox();
        checkLectura = new javax.swing.JCheckBox();
        checkDeporte = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre:");

        jLabel2.setText("Apellidos:");

        jLabel3.setText("Sexo:");

        jLabel4.setText("Aficiones:");

        botonGuardar.setText("GUARDAR");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        buttonGroup1.add(botonHombre);
        botonHombre.setText("Hombre");

        buttonGroup1.add(botonMujer);
        botonMujer.setText("Mujer");

        checkCine.setText("Cine");
        checkCine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkCineActionPerformed(evt);
            }
        });

        checkViajes.setText("Viajes");
        checkViajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkViajesActionPerformed(evt);
            }
        });

        checkLectura.setText("Lectura");
        checkLectura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkLecturaActionPerformed(evt);
            }
        });

        checkDeporte.setText("Deporte");
        checkDeporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkDeporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(campoApellidos)
                        .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonHombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonMujer))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkCine)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkViajes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkLectura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkDeporte)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(botonHombre)
                    .addComponent(botonMujer))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(checkCine)
                    .addComponent(checkViajes)
                    .addComponent(checkLectura)
                    .addComponent(checkDeporte))
                .addGap(41, 41, 41)
                .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    ArrayList<String> listaActividades = new ArrayList<>();

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        int seleccion = jFileChooser1.showSaveDialog(botonGuardar);
        if (seleccion == 0){
            try {
                PrintWriter writer = null;
                File archivo = jFileChooser1.getSelectedFile();

                writer = new PrintWriter(archivo);
                writer.append("Tu nombre es: " + campoNombre.getText() + " " + campoApellidos.getText());

                if (botonHombre.isSelected()) {
                    writer.append("\nSu sexo es: " + botonHombre.getText());
                } else if (botonMujer.isSelected()) {
                    writer.append("\nSu sexo es: " + botonMujer.getText());
                } else writer.append("\nNo has seleccionado ningun sexo");

                writer.append("\nTus actividades favoritas son: ");
                int contador = 0;
                for (String a : listaActividades) {
                    contador += 1;
                    writer.append(a);

                    if (contador == listaActividades.size()) {
                        break;
                    }
                    writer.append(", ");
                }

                writer.close();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(frame1.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void checkCineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkCineActionPerformed
        // TODO add your handling code here:
        listaActividades.add(checkCine.getText());

    }//GEN-LAST:event_checkCineActionPerformed

    private void checkViajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkViajesActionPerformed
        // TODO add your handling code here:
        listaActividades.add(checkViajes.getText());

    }//GEN-LAST:event_checkViajesActionPerformed

    private void checkLecturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkLecturaActionPerformed
        // TODO add your handling code here:
        listaActividades.add(checkLectura.getText());

    }//GEN-LAST:event_checkLecturaActionPerformed

    private void checkDeporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkDeporteActionPerformed
        // TODO add your handling code here:
        listaActividades.add(checkDeporte.getText());


    }//GEN-LAST:event_checkDeporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardar;
    private javax.swing.JRadioButton botonHombre;
    private javax.swing.JRadioButton botonMujer;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField campoApellidos;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JCheckBox checkCine;
    private javax.swing.JCheckBox checkDeporte;
    private javax.swing.JCheckBox checkLectura;
    private javax.swing.JCheckBox checkViajes;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
