/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Paquete;

/**
 *
 * @author dam2
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTurno = new javax.swing.ButtonGroup();
        grupoSexo = new javax.swing.ButtonGroup();
        tarde = new javax.swing.JRadioButton();
        mañana = new javax.swing.JRadioButton();
        noche = new javax.swing.JRadioButton();
        hombre = new javax.swing.JRadioButton();
        mujer = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        grupoTurno.add(tarde);
        tarde.setText("Tarde");
        tarde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tardeActionPerformed(evt);
            }
        });

        grupoTurno.add(mañana);
        mañana.setText("Mañana");
        mañana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mañanaActionPerformed(evt);
            }
        });

        grupoTurno.add(noche);
        noche.setText("Noche");

        grupoSexo.add(hombre);
        hombre.setText("Hombre");

        grupoSexo.add(mujer);
        mujer.setText("Mujer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mujer)
                    .addComponent(hombre)
                    .addComponent(mañana)
                    .addComponent(noche)
                    .addComponent(tarde))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(mañana)
                .addGap(30, 30, 30)
                .addComponent(tarde)
                .addGap(29, 29, 29)
                .addComponent(noche)
                .addGap(53, 53, 53)
                .addComponent(hombre)
                .addGap(31, 31, 31)
                .addComponent(mujer)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mañanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mañanaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mañanaActionPerformed

    private void tardeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tardeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tardeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupoSexo;
    private javax.swing.ButtonGroup grupoTurno;
    private javax.swing.JRadioButton hombre;
    private javax.swing.JRadioButton mañana;
    private javax.swing.JRadioButton mujer;
    private javax.swing.JRadioButton noche;
    private javax.swing.JRadioButton tarde;
    // End of variables declaration//GEN-END:variables
}
