/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paquete;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import jdk.dynalink.linker.support.Guards;

/**
 *
 * @author dam2
 */
public class IsertarImagenes extends javax.swing.JFrame {

    /**
     * Creates new form IsertarImagenes
     */
    public IsertarImagenes() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        gatoBtn = new javax.swing.JButton();
        perroBtn = new javax.swing.JButton();
        jRadio100x100 = new javax.swing.JRadioButton();
        jRadio200x200 = new javax.swing.JRadioButton();
        jRadio300x300 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        gatoBtn.setText("Gato");
        gatoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gatoBtnActionPerformed(evt);
            }
        });

        perroBtn.setText("Perro");
        perroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perroBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadio100x100);
        jRadio100x100.setText("100x100");
        jRadio100x100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio100x100ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadio200x200);
        jRadio200x200.setText("200x200");
        jRadio200x200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio200x200ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadio300x300);
        jRadio300x300.setText("300x300");
        jRadio300x300.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio300x300ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gatoBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(perroBtn))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadio300x300, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadio200x200, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadio100x100, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jRadio100x100)
                        .addGap(27, 27, 27)
                        .addComponent(jRadio200x200)
                        .addGap(28, 28, 28)
                        .addComponent(jRadio300x300)))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gatoBtn)
                    .addComponent(perroBtn))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
       String url = "";
    private void gatoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gatoBtnActionPerformed
        // TODO add your handling code here:
        url = "/img/gato.jpg";
        cargarImagen(url,jLabel1.getWidth(),jLabel1.getHeight());
    }//GEN-LAST:event_gatoBtnActionPerformed

    private void perroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perroBtnActionPerformed
        // TODO add your handling code here:
        url = "/img/perro.jpg";
        cargarImagen(url, jLabel1.getWidth(), jLabel1.getHeight());

    }//GEN-LAST:event_perroBtnActionPerformed

    private void jRadio300x300ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio300x300ActionPerformed
        // TODO add your handling code here:
        cargarImagen(url, 300, 300);

    }//GEN-LAST:event_jRadio300x300ActionPerformed

    private void jRadio200x200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio200x200ActionPerformed
        // TODO add your handling code here:
         cargarImagen(url, 200, 200);

    }//GEN-LAST:event_jRadio200x200ActionPerformed

    private void jRadio100x100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio100x100ActionPerformed
        // TODO add your handling code here:
          cargarImagen(url, 100, 100);
    }//GEN-LAST:event_jRadio100x100ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IsertarImagenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IsertarImagenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IsertarImagenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IsertarImagenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IsertarImagenes().setVisible(true);
            }
        });
    }
    public  void cargarImagen(String archivo, int ancho, int alto){
        ImageIcon icon = new ImageIcon(getClass().getResource(archivo));
        Icon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));
        jLabel1.setIcon(icono);
        
    
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton gatoBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadio100x100;
    private javax.swing.JRadioButton jRadio200x200;
    private javax.swing.JRadioButton jRadio300x300;
    private javax.swing.JButton perroBtn;
    // End of variables declaration//GEN-END:variables
}

