/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Paquete;

/**
 *
 * @author dam2
 */
public class frame1 extends javax.swing.JFrame {

    /**
     * Creates new form frame1
     */
    public frame1() {
        initComponents();
        pestanias.setEnabledAt(1, false);
        pestanias.setEnabledAt(2, false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pestanias = new javax.swing.JTabbedPane();
        datosConductor = new javax.swing.JPanel();
        nombre = new javax.swing.JLabel();
        apellidos = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        campoApellidos = new javax.swing.JTextField();
        tickCoche = new javax.swing.JCheckBox();
        tickMonovolumen = new javax.swing.JCheckBox();
        coche = new javax.swing.JPanel();
        camion = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nombre.setText("Nombre");

        apellidos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        apellidos.setText("Apellidos");

        tickCoche.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tickCoche.setText("Coche");
        tickCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tickCocheActionPerformed(evt);
            }
        });

        tickMonovolumen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tickMonovolumen.setText("Monovolumen");
        tickMonovolumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tickMonovolumenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout datosConductorLayout = new javax.swing.GroupLayout(datosConductor);
        datosConductor.setLayout(datosConductorLayout);
        datosConductorLayout.setHorizontalGroup(
            datosConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosConductorLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(datosConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(datosConductorLayout.createSequentialGroup()
                        .addComponent(nombre)
                        .addGap(18, 18, 18)
                        .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(datosConductorLayout.createSequentialGroup()
                        .addComponent(apellidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(datosConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tickMonovolumen)
                            .addComponent(tickCoche)
                            .addComponent(campoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        datosConductorLayout.setVerticalGroup(
            datosConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosConductorLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(datosConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(datosConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidos)
                    .addComponent(campoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(tickCoche)
                .addGap(18, 18, 18)
                .addComponent(tickMonovolumen)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pestanias.addTab("Datos conductor", new javax.swing.ImageIcon(getClass().getResource("/img/cara.png")), datosConductor); // NOI18N

        javax.swing.GroupLayout cocheLayout = new javax.swing.GroupLayout(coche);
        coche.setLayout(cocheLayout);
        cocheLayout.setHorizontalGroup(
            cocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
        );
        cocheLayout.setVerticalGroup(
            cocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );

        pestanias.addTab("Coche", new javax.swing.ImageIcon(getClass().getResource("/img/coche.png")), coche); // NOI18N

        javax.swing.GroupLayout camionLayout = new javax.swing.GroupLayout(camion);
        camion.setLayout(camionLayout);
        camionLayout.setHorizontalGroup(
            camionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
        );
        camionLayout.setVerticalGroup(
            camionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );

        pestanias.addTab("Monovolumen", new javax.swing.ImageIcon(getClass().getResource("/img/monovolumen.png")), camion); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pestanias, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pestanias)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tickCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tickCocheActionPerformed
        // TODO add your handling code here:
        if (tickCoche.isSelected()) {
            pestanias.setEnabledAt(1, true);
        } else pestanias.setEnabledAt(1, false);

    }//GEN-LAST:event_tickCocheActionPerformed

    private void tickMonovolumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tickMonovolumenActionPerformed
        // TODO add your handling code here:
        if (tickMonovolumen.isSelected()) {
            pestanias.setEnabledAt(2, true);
        } else pestanias.setEnabledAt(2, false);

    }//GEN-LAST:event_tickMonovolumenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellidos;
    private javax.swing.JPanel camion;
    private javax.swing.JTextField campoApellidos;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JPanel coche;
    private javax.swing.JPanel datosConductor;
    private javax.swing.JLabel nombre;
    private javax.swing.JTabbedPane pestanias;
    private javax.swing.JCheckBox tickCoche;
    private javax.swing.JCheckBox tickMonovolumen;
    // End of variables declaration//GEN-END:variables
}
