/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paquete;

import javax.swing.SpinnerNumberModel;

/**
 *
 * @author dam2
 */
public class Ej1 extends javax.swing.JFrame {

    /**
     * Creates new form Ej1
     */
    public Ej1() {
        initComponents();
        panelNotasCam.setVisible(false);
        panelNotasEOI.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        campoApellidos = new javax.swing.JTextField();
        campoNivel = new javax.swing.JTextField();
        peastannas = new javax.swing.JTabbedPane();
        panelCambridge = new javax.swing.JPanel();
        radioB1Cam = new javax.swing.JRadioButton();
        radioB2Cam = new javax.swing.JRadioButton();
        panelNotasCam = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        spinerWriting = new javax.swing.JSpinner();
        spinerSpeaking = new javax.swing.JSpinner();
        spinerReading = new javax.swing.JSpinner();
        spinerListening = new javax.swing.JSpinner();
        botonNotaCam = new javax.swing.JButton();
        panelEOI = new javax.swing.JPanel();
        radioB1EOI = new javax.swing.JRadioButton();
        radioB2EOI = new javax.swing.JRadioButton();
        panelNotasEOI = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        spinerWriting1 = new javax.swing.JSpinner();
        spinerSpeaking1 = new javax.swing.JSpinner();
        spinerReading1 = new javax.swing.JSpinner();
        spinerListening1 = new javax.swing.JSpinner();
        spinerMediation = new javax.swing.JSpinner();
        botonNotaEOI = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Examenes inglés"); // NOI18N

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellidos");

        jLabel3.setText("Nivel de ingles");

        campoNombre.setText("Nombre");
        campoNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoNombreMouseClicked(evt);
            }
        });
        campoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreActionPerformed(evt);
            }
        });

        campoApellidos.setText("Apellidos");
        campoApellidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoApellidosMouseClicked(evt);
            }
        });

        campoNivel.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(campoNombre)
                    .addComponent(campoNivel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        buttonGroup1.add(radioB1Cam);
        radioB1Cam.setText("B1");
        radioB1Cam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioB1CamActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioB2Cam);
        radioB2Cam.setText("B2");
        radioB2Cam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioB2CamActionPerformed(evt);
            }
        });

        jLabel4.setText("Nota writing");

        jLabel5.setText("Nota speaking");

        jLabel6.setText("Nota reading");

        jLabel7.setText("Nota listening");

        spinerWriting.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinerWritingStateChanged(evt);
            }
        });

        spinerSpeaking.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinerSpeakingStateChanged(evt);
            }
        });

        spinerReading.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinerReadingStateChanged(evt);
            }
        });

        spinerListening.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinerListeningStateChanged(evt);
            }
        });

        botonNotaCam.setText("Calcular nota");

        javax.swing.GroupLayout panelNotasCamLayout = new javax.swing.GroupLayout(panelNotasCam);
        panelNotasCam.setLayout(panelNotasCamLayout);
        panelNotasCamLayout.setHorizontalGroup(
            panelNotasCamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNotasCamLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(botonNotaCam, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(panelNotasCamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelNotasCamLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(panelNotasCamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(jLabel4))
                    .addGap(54, 54, 54)
                    .addGroup(panelNotasCamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(spinerWriting)
                        .addComponent(spinerSpeaking)
                        .addComponent(spinerReading)
                        .addComponent(spinerListening, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(78, Short.MAX_VALUE)))
        );
        panelNotasCamLayout.setVerticalGroup(
            panelNotasCamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNotasCamLayout.createSequentialGroup()
                .addContainerGap(191, Short.MAX_VALUE)
                .addComponent(botonNotaCam, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(panelNotasCamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelNotasCamLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(panelNotasCamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(spinerWriting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(panelNotasCamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(spinerSpeaking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(panelNotasCamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(spinerReading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(panelNotasCamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(spinerListening, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(106, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout panelCambridgeLayout = new javax.swing.GroupLayout(panelCambridge);
        panelCambridge.setLayout(panelCambridgeLayout);
        panelCambridgeLayout.setHorizontalGroup(
            panelCambridgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCambridgeLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelCambridgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelNotasCam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelCambridgeLayout.createSequentialGroup()
                        .addComponent(radioB1Cam)
                        .addGap(18, 18, 18)
                        .addComponent(radioB2Cam)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        panelCambridgeLayout.setVerticalGroup(
            panelCambridgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCambridgeLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelCambridgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioB1Cam)
                    .addComponent(radioB2Cam))
                .addGap(18, 18, 18)
                .addComponent(panelNotasCam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        peastannas.addTab("Cambridge", panelCambridge);

        buttonGroup1.add(radioB1EOI);
        radioB1EOI.setText("B1");
        radioB1EOI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioB1EOIActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioB2EOI);
        radioB2EOI.setText("B2");
        radioB2EOI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioB2EOIActionPerformed(evt);
            }
        });

        jLabel8.setText("Nota writing");

        jLabel9.setText("Nota speaking");

        jLabel10.setText("Nota reading");

        jLabel11.setText("Nota listening");

        jLabel12.setText("Nota mediation");

        spinerWriting1.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));
        spinerWriting1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinerWriting1StateChanged(evt);
            }
        });

        spinerSpeaking1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinerSpeaking1StateChanged(evt);
            }
        });

        spinerReading1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinerReading1StateChanged(evt);
            }
        });

        spinerListening1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinerListening1StateChanged(evt);
            }
        });

        spinerMediation.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinerMediationStateChanged(evt);
            }
        });

        botonNotaEOI.setText("Calcular nota");

        javax.swing.GroupLayout panelNotasEOILayout = new javax.swing.GroupLayout(panelNotasEOI);
        panelNotasEOI.setLayout(panelNotasEOILayout);
        panelNotasEOILayout.setHorizontalGroup(
            panelNotasEOILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNotasEOILayout.createSequentialGroup()
                .addGroup(panelNotasEOILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNotasEOILayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelNotasEOILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelNotasEOILayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(spinerSpeaking1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelNotasEOILayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(46, 46, 46)
                                .addComponent(spinerMediation, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelNotasEOILayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(botonNotaEOI, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(panelNotasEOILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelNotasEOILayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(panelNotasEOILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel11)
                        .addComponent(jLabel10)
                        .addComponent(jLabel8))
                    .addGap(56, 56, 56)
                    .addGroup(panelNotasEOILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(spinerWriting1)
                        .addComponent(spinerReading1)
                        .addComponent(spinerListening1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(78, Short.MAX_VALUE)))
        );
        panelNotasEOILayout.setVerticalGroup(
            panelNotasEOILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNotasEOILayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(panelNotasEOILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(spinerSpeaking1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addGroup(panelNotasEOILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(spinerMediation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(botonNotaEOI, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(panelNotasEOILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelNotasEOILayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(panelNotasEOILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(spinerWriting1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(62, 62, 62)
                    .addGroup(panelNotasEOILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(spinerReading1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(panelNotasEOILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(spinerListening1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(140, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout panelEOILayout = new javax.swing.GroupLayout(panelEOI);
        panelEOI.setLayout(panelEOILayout);
        panelEOILayout.setHorizontalGroup(
            panelEOILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEOILayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelEOILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelNotasEOI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelEOILayout.createSequentialGroup()
                        .addComponent(radioB1EOI)
                        .addGap(18, 18, 18)
                        .addComponent(radioB2EOI)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        panelEOILayout.setVerticalGroup(
            panelEOILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEOILayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelEOILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioB1EOI)
                    .addComponent(radioB2EOI))
                .addGap(18, 18, 18)
                .addComponent(panelNotasEOI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        peastannas.addTab("EOI", panelEOI);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(peastannas, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(peastannas))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_campoNombreActionPerformed

    private void campoNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoNombreMouseClicked
        // TODO add your handling code here:
        campoNombre.setText("");
    }//GEN-LAST:event_campoNombreMouseClicked

    private void campoApellidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoApellidosMouseClicked
        // TODO add your handling code here:
        campoApellidos.setText("");
    }//GEN-LAST:event_campoApellidosMouseClicked

    private void radioB1CamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioB1CamActionPerformed
        // TODO add your handling code here:
        panelNotasCam.setVisible(true);
        
        SpinnerNumberModel spB1 = new SpinnerNumberModel();
        spB1.setMinimum(0);
        spB1.setMaximum(170);
        spinerListening.setModel(spB1);
        
        SpinnerNumberModel spB11 = new SpinnerNumberModel();
        spB11.setMinimum(0);
        spB11.setMaximum(170);
        spinerReading.setModel(spB11);
        
        SpinnerNumberModel spB12 = new SpinnerNumberModel();
        spB12.setMinimum(0);
        spB12.setMaximum(170);
        spinerSpeaking.setModel(spB12);
        
        SpinnerNumberModel spB13 = new SpinnerNumberModel();
        spB13.setMinimum(0);
        spB13.setMaximum(170);
        spinerWriting.setModel(spB13);
        
    }//GEN-LAST:event_radioB1CamActionPerformed

    private void radioB2CamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioB2CamActionPerformed
        // TODO add your handling code here:
        panelNotasCam.setVisible(true);
        
        SpinnerNumberModel spB2 = new SpinnerNumberModel();
        spB2.setMinimum(0);
        spB2.setMaximum(190);
        spinerListening.setModel(spB2);
        
        SpinnerNumberModel spB21 = new SpinnerNumberModel();
        spB21.setMinimum(0);
        spB21.setMaximum(190);
        spinerReading.setModel(spB21);
        
        SpinnerNumberModel spB22 = new SpinnerNumberModel();
        spB22.setMinimum(0);
        spB22.setMaximum(190);
        spinerSpeaking.setModel(spB22);
        
        SpinnerNumberModel spB23 = new SpinnerNumberModel();
        spB23.setMinimum(0);
        spB23.setMaximum(190);
        spinerWriting.setModel(spB23);
    }//GEN-LAST:event_radioB2CamActionPerformed

    private void spinerWritingStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinerWritingStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_spinerWritingStateChanged

    private void spinerSpeakingStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinerSpeakingStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_spinerSpeakingStateChanged

    private void spinerReadingStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinerReadingStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_spinerReadingStateChanged

    private void spinerListeningStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinerListeningStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_spinerListeningStateChanged

    private void spinerWriting1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinerWriting1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_spinerWriting1StateChanged

    private void spinerSpeaking1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinerSpeaking1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_spinerSpeaking1StateChanged

    private void spinerReading1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinerReading1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_spinerReading1StateChanged

    private void spinerListening1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinerListening1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_spinerListening1StateChanged

    private void spinerMediationStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinerMediationStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_spinerMediationStateChanged

    private void radioB1EOIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioB1EOIActionPerformed
        // TODO add your handling code here:
        panelNotasEOI.setVisible(true);
        
        SpinnerNumberModel spB1E = new SpinnerNumberModel(0.0, 0.0, 10.0, 0.1);
        spinerListening1.setModel(spB1E);
        
        SpinnerNumberModel spB11E = new SpinnerNumberModel(0.0, 0.0, 10.0, 0.1);
        spinerReading1.setModel(spB11E);
        
        SpinnerNumberModel spB12E = new SpinnerNumberModel(0.0, 0.0, 10.0, 0.1);
        spinerSpeaking1.setModel(spB12E);
        
        SpinnerNumberModel spB13E = new SpinnerNumberModel(0.0, 0.0, 10.0, 0.1);
        spinerWriting1.setModel(spB13E);
        
        SpinnerNumberModel spB14E = new SpinnerNumberModel(0.0, 0.0, 10.0, 0.1);
        spinerMediation.setModel(spB14E);
    }//GEN-LAST:event_radioB1EOIActionPerformed

    private void radioB2EOIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioB2EOIActionPerformed
        // TODO add your handling code here:
        panelNotasEOI.setVisible(true);
        
        SpinnerNumberModel spB2E = new SpinnerNumberModel(0.0, 0.0, 10, 0.1);
        spinerListening1.setModel(spB2E);
        
        SpinnerNumberModel spB21E = new SpinnerNumberModel(0.0, 0.0, 10.0, 0.1);
        spinerReading1.setModel(spB21E);
        
        SpinnerNumberModel spB22E = new SpinnerNumberModel(0.0, 0.0, 10.0, 0.1);
        spinerSpeaking1.setModel(spB22E);
        
        SpinnerNumberModel spB23E = new SpinnerNumberModel(0.0, 0.0, 10.0, 0.1);
        spinerWriting1.setModel(spB23E);
        
        SpinnerNumberModel spB24E = new SpinnerNumberModel(0.0, 0.0, 10.0, 0.1);
        spinerMediation.setModel(spB24E);
    }//GEN-LAST:event_radioB2EOIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ej1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ej1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ej1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ej1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Ej1().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonNotaCam;
    private javax.swing.JButton botonNotaEOI;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField campoApellidos;
    private javax.swing.JTextField campoNivel;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel panelCambridge;
    private javax.swing.JPanel panelEOI;
    private javax.swing.JPanel panelNotasCam;
    private javax.swing.JPanel panelNotasEOI;
    private javax.swing.JTabbedPane peastannas;
    private javax.swing.JRadioButton radioB1Cam;
    private javax.swing.JRadioButton radioB1EOI;
    private javax.swing.JRadioButton radioB2Cam;
    private javax.swing.JRadioButton radioB2EOI;
    private javax.swing.JSpinner spinerListening;
    private javax.swing.JSpinner spinerListening1;
    private javax.swing.JSpinner spinerMediation;
    private javax.swing.JSpinner spinerReading;
    private javax.swing.JSpinner spinerReading1;
    private javax.swing.JSpinner spinerSpeaking;
    private javax.swing.JSpinner spinerSpeaking1;
    private javax.swing.JSpinner spinerWriting;
    private javax.swing.JSpinner spinerWriting1;
    // End of variables declaration//GEN-END:variables
}
