/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Paquete;

import javax.swing.JOptionPane;

/**
 *
 * @author dam2
 */
public class FrameEvento extends javax.swing.JFrame {

    /**
     * Creates new form FrameEvento
     */
    public FrameEvento() {
        initComponents();

        panelCaracteristicasCongreso.setVisible(false);
        panelCaracteristicasBoda.setVisible(false);
        jTabbedPane1.setEnabledAt(0, false);
        jTabbedPane1.setEnabledAt(1, false);

        cBoxParque.setVisible(false);
        cBoxTransporteBoda.setVisible(false);
        cBoxTransporte.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupEventoAceptado = new javax.swing.ButtonGroup();
        buttonGroup1TipoEvento = new javax.swing.ButtonGroup();
        buttonGroup1SalonHoteles = new javax.swing.ButtonGroup();
        buttonGroup1TipoMenu = new javax.swing.ButtonGroup();
        campoNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        campoPrecioEvento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rBotonAceptadoSi = new javax.swing.JRadioButton();
        rBotonAceptadoNo = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        rBotonCongreso = new javax.swing.JRadioButton();
        rBotonBoda = new javax.swing.JRadioButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelCongreso = new javax.swing.JPanel();
        panelCaracteristicasCongreso = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        spinnerCantidadAsistentes = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cBoxSalon = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cBoxTransporte = new javax.swing.JCheckBox();
        cBoxAperitivo = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        panelBoda = new javax.swing.JPanel();
        panelCaracteristicasBoda = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        spinnerAdultos = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        spinnerNinnos = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        comboBoxLugarBoda = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        rBotonsalonHotel1 = new javax.swing.JRadioButton();
        rBotonsalonHotel2 = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        menuBasic = new javax.swing.JRadioButton();
        menuElegant = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        cBoxTransporteBoda = new javax.swing.JCheckBox();
        cBoxOrquestaBoda = new javax.swing.JCheckBox();
        cBoxDisco = new javax.swing.JCheckBox();
        cBoxParque = new javax.swing.JCheckBox();
        botonFinalizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre:");

        campoPrecioEvento.setText("0");
        campoPrecioEvento.setEnabled(false);

        jLabel2.setText("Precio evento:");

        jLabel3.setText("Aceptado");

        buttonGroupEventoAceptado.add(rBotonAceptadoSi);
        rBotonAceptadoSi.setText("Si");
        rBotonAceptadoSi.setEnabled(false);

        buttonGroupEventoAceptado.add(rBotonAceptadoNo);
        rBotonAceptadoNo.setText("No");
        rBotonAceptadoNo.setEnabled(false);

        jLabel4.setText("Tipo evento:");

        buttonGroup1TipoEvento.add(rBotonCongreso);
        rBotonCongreso.setText("Congreso");
        rBotonCongreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBotonCongresoActionPerformed(evt);
            }
        });

        buttonGroup1TipoEvento.add(rBotonBoda);
        rBotonBoda.setText("Boda");
        rBotonBoda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBotonBodaActionPerformed(evt);
            }
        });

        jLabel5.setText("Numero asistentes:");

        spinnerCantidadAsistentes.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        spinnerCantidadAsistentes.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerCantidadAsistentesStateChanged(evt);
            }
        });

        jLabel6.setText("Fecha inicio evento:");

        jLabel7.setText("Fecha fin evento:");

        jLabel8.setText("Numero de días:");

        jLabel9.setText("Salón:");

        cBoxSalon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enebros (800€)", "Acacias (900€)" }));
        cBoxSalon.setSelectedIndex(-1);
        cBoxSalon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cBoxSalonItemStateChanged(evt);
            }
        });
        cBoxSalon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxSalonActionPerformed(evt);
            }
        });

        jLabel10.setText("Extras:");

        cBoxTransporte.setText("Transporte (Minimo 30 personas, maximo 100 - 10€ / persona)");
        cBoxTransporte.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cBoxTransporteItemStateChanged(evt);
            }
        });
        cBoxTransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxTransporteActionPerformed(evt);
            }
        });

        cBoxAperitivo.setText("Aperitivo (15€ / persona)");
        cBoxAperitivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxAperitivoActionPerformed(evt);
            }
        });

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout panelCaracteristicasCongresoLayout = new javax.swing.GroupLayout(panelCaracteristicasCongreso);
        panelCaracteristicasCongreso.setLayout(panelCaracteristicasCongresoLayout);
        panelCaracteristicasCongresoLayout.setHorizontalGroup(
            panelCaracteristicasCongresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCaracteristicasCongresoLayout.createSequentialGroup()
                .addGroup(panelCaracteristicasCongresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCaracteristicasCongresoLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(panelCaracteristicasCongresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cBoxTransporte)
                            .addComponent(cBoxAperitivo)))
                    .addGroup(panelCaracteristicasCongresoLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(147, Short.MAX_VALUE))
            .addGroup(panelCaracteristicasCongresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCaracteristicasCongresoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(panelCaracteristicasCongresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelCaracteristicasCongresoLayout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(18, 18, 18)
                            .addComponent(cBoxSalon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel8)
                        .addComponent(jLabel7)
                        .addComponent(jLabel6)
                        .addGroup(panelCaracteristicasCongresoLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(spinnerCantidadAsistentes, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel10))
                    .addContainerGap(349, Short.MAX_VALUE)))
        );
        panelCaracteristicasCongresoLayout.setVerticalGroup(
            panelCaracteristicasCongresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCaracteristicasCongresoLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(cBoxAperitivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cBoxTransporte)
                .addGap(174, 174, 174))
            .addGroup(panelCaracteristicasCongresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCaracteristicasCongresoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(panelCaracteristicasCongresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(spinnerCantidadAsistentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jLabel6)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel7)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel8)
                    .addGap(18, 18, 18)
                    .addGroup(panelCaracteristicasCongresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(cBoxSalon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jLabel10)
                    .addContainerGap(219, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout panelCongresoLayout = new javax.swing.GroupLayout(panelCongreso);
        panelCongreso.setLayout(panelCongresoLayout);
        panelCongresoLayout.setHorizontalGroup(
            panelCongresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCongresoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCaracteristicasCongreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCongresoLayout.setVerticalGroup(
            panelCongresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCongresoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCaracteristicasCongreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Congreso", panelCongreso);

        jLabel13.setText("Canitdad de asistentes:");

        jLabel14.setText("Adultos");

        spinnerAdultos.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        spinnerAdultos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerAdultosStateChanged(evt);
            }
        });

        jLabel15.setText("Niños");

        spinnerNinnos.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        spinnerNinnos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerNinnosStateChanged(evt);
            }
        });

        jLabel16.setText("Fecha evento:");

        comboBoxLugarBoda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hotel la reconquista", "Hotel Maria Luisa", "Hotel City" }));
        comboBoxLugarBoda.setSelectedIndex(-1);
        comboBoxLugarBoda.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxLugarBodaItemStateChanged(evt);
            }
        });

        jLabel17.setText("Eleccion del lugar:");

        buttonGroup1SalonHoteles.add(rBotonsalonHotel1);
        rBotonsalonHotel1.setText("Salón...");

        buttonGroup1SalonHoteles.add(rBotonsalonHotel2);
        rBotonsalonHotel2.setText("Salón...");

        jLabel18.setText("Eleccion del menú:");

        buttonGroup1TipoMenu.add(menuBasic);
        menuBasic.setText("Menú basic (60€ adultos / 30€ niños)");
        menuBasic.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                menuBasicItemStateChanged(evt);
            }
        });
        menuBasic.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                menuBasicStateChanged(evt);
            }
        });
        menuBasic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBasicActionPerformed(evt);
            }
        });

        buttonGroup1TipoMenu.add(menuElegant);
        menuElegant.setText("Menú elegant (100€ adultos / 50€ niños)");
        menuElegant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuElegantActionPerformed(evt);
            }
        });

        jLabel19.setText("Extras:");

        cBoxTransporteBoda.setText("Transporte (Minimo 50 personas, maximo 200 - 8€ / persona)");
        cBoxTransporteBoda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxTransporteBodaActionPerformed(evt);
            }
        });

        cBoxOrquestaBoda.setText("Orquesta");

        cBoxDisco.setText("Disco");

        cBoxParque.setText("Parque infantil (100€ - solo si hay niños)");

        javax.swing.GroupLayout panelCaracteristicasBodaLayout = new javax.swing.GroupLayout(panelCaracteristicasBoda);
        panelCaracteristicasBoda.setLayout(panelCaracteristicasBodaLayout);
        panelCaracteristicasBodaLayout.setHorizontalGroup(
            panelCaracteristicasBodaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCaracteristicasBodaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(25, 25, 25)
                .addComponent(spinnerAdultos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(spinnerNinnos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCaracteristicasBodaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelCaracteristicasBodaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rBotonsalonHotel2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rBotonsalonHotel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98))
            .addGroup(panelCaracteristicasBodaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCaracteristicasBodaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(panelCaracteristicasBodaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelCaracteristicasBodaLayout.createSequentialGroup()
                            .addComponent(jLabel19)
                            .addGap(18, 18, 18)
                            .addGroup(panelCaracteristicasBodaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cBoxOrquestaBoda)
                                .addComponent(cBoxDisco)
                                .addComponent(cBoxParque)
                                .addComponent(cBoxTransporteBoda)))
                        .addComponent(jLabel16)
                        .addGroup(panelCaracteristicasBodaLayout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addGap(18, 18, 18)
                            .addComponent(comboBoxLugarBoda, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelCaracteristicasBodaLayout.createSequentialGroup()
                            .addComponent(jLabel18)
                            .addGap(18, 18, 18)
                            .addGroup(panelCaracteristicasBodaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(menuElegant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(menuBasic, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))))
                    .addContainerGap(154, Short.MAX_VALUE)))
        );
        panelCaracteristicasBodaLayout.setVerticalGroup(
            panelCaracteristicasBodaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCaracteristicasBodaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCaracteristicasBodaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerAdultos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(spinnerNinnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addGap(37, 37, 37)
                .addComponent(rBotonsalonHotel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rBotonsalonHotel2)
                .addContainerGap(301, Short.MAX_VALUE))
            .addGroup(panelCaracteristicasBodaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCaracteristicasBodaLayout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(jLabel16)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(panelCaracteristicasBodaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(comboBoxLugarBoda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(59, 59, 59)
                    .addGroup(panelCaracteristicasBodaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(menuBasic))
                    .addGap(18, 18, 18)
                    .addComponent(menuElegant)
                    .addGap(18, 18, 18)
                    .addGroup(panelCaracteristicasBodaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(cBoxTransporteBoda))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(cBoxOrquestaBoda)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(cBoxDisco)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(cBoxParque)
                    .addContainerGap(111, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout panelBodaLayout = new javax.swing.GroupLayout(panelBoda);
        panelBoda.setLayout(panelBodaLayout);
        panelBodaLayout.setHorizontalGroup(
            panelBodaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBodaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCaracteristicasBoda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBodaLayout.setVerticalGroup(
            panelBodaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBodaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCaracteristicasBoda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Boda", panelBoda);

        botonFinalizar.setText("FINALIZAR RESERVA");
        botonFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFinalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(campoPrecioEvento, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rBotonAceptadoSi)
                                .addGap(18, 18, 18)
                                .addComponent(rBotonAceptadoNo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rBotonCongreso)
                                .addGap(18, 18, 18)
                                .addComponent(rBotonBoda)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoPrecioEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(rBotonAceptadoSi)
                            .addComponent(rBotonAceptadoNo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(botonFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rBotonCongreso)
                    .addComponent(rBotonBoda))
                .addGap(34, 34, 34)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void rBotonCongresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBotonCongresoActionPerformed
        // TODO add your handling code here:
        panelCaracteristicasCongreso.setVisible(true);
        jTabbedPane1.setEnabledAt(0, true);
        jTabbedPane1.setEnabledAt(1, false);
        campoPrecioEvento.setText(String.valueOf(0));

    }//GEN-LAST:event_rBotonCongresoActionPerformed

    private void rBotonBodaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBotonBodaActionPerformed
        // TODO add your handling code here:
        panelCaracteristicasBoda.setVisible(true);
        jTabbedPane1.setEnabledAt(1, true);
        jTabbedPane1.setEnabledAt(0, false);
        campoPrecioEvento.setText(String.valueOf(0));

    }//GEN-LAST:event_rBotonBodaActionPerformed

    private void cBoxSalonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxSalonActionPerformed

    }//GEN-LAST:event_cBoxSalonActionPerformed

    private void cBoxSalonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cBoxSalonItemStateChanged
        // TODO add your handling code here:
        if (cBoxSalon.getSelectedIndex() == 0) {
            campoPrecioEvento.setText(String.valueOf(800));
        } else {
            campoPrecioEvento.setText(String.valueOf(900));
        }
    }//GEN-LAST:event_cBoxSalonItemStateChanged

    private void cBoxTransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxTransporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cBoxTransporteActionPerformed

    private void cBoxTransporteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cBoxTransporteItemStateChanged
        // TODO add your handling code here:
        if (cBoxTransporte.isSelected() && (int) spinnerCantidadAsistentes.getValue() > 30 && (int) spinnerCantidadAsistentes.getValue() < 100) {
            int precioNuevo = Integer.valueOf(campoPrecioEvento.getText()) + (int) spinnerCantidadAsistentes.getValue() * 10;
            campoPrecioEvento.setText(String.valueOf(precioNuevo));

        } else if (!cBoxTransporte.isSelected()) {
            int precioNuevo = Integer.valueOf(campoPrecioEvento.getText()) - (int) spinnerCantidadAsistentes.getValue() * 10;
            campoPrecioEvento.setText(String.valueOf(precioNuevo));
        }
    }//GEN-LAST:event_cBoxTransporteItemStateChanged

    private void cBoxAperitivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxAperitivoActionPerformed
        // TODO add your handling code here:
        if (cBoxAperitivo.isSelected()) {
            int precioNuevo = Integer.valueOf(campoPrecioEvento.getText()) + (int) spinnerCantidadAsistentes.getValue() * 15;
            campoPrecioEvento.setText(String.valueOf(precioNuevo));

        } else {
            int precioNuevo = Integer.valueOf(campoPrecioEvento.getText()) - (int) spinnerCantidadAsistentes.getValue() * 15;
            campoPrecioEvento.setText(String.valueOf(precioNuevo));
        }
    }//GEN-LAST:event_cBoxAperitivoActionPerformed

    private void cBoxTransporteBodaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxTransporteBodaActionPerformed
        // TODO add your handling code here:
        if ((int)spinnerAdultos.getValue() + (int)spinnerNinnos.getValue() > 50 && (int)spinnerAdultos.getValue() + (int)spinnerNinnos.getValue() < 200) {
            cBoxTransporteBoda.setVisible(true);
        }
    }//GEN-LAST:event_cBoxTransporteBodaActionPerformed

    private void menuElegantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuElegantActionPerformed
        // TODO add your handling code here:
        if (!menuElegant.isSelected()) {
            campoPrecioEvento.setText(String.valueOf(
                    Integer.parseInt(campoPrecioEvento.getText())
                    + (int) spinnerAdultos.getValue() * 60
                    + (int) spinnerNinnos.getValue() * 30
            ));
            
        }

    }//GEN-LAST:event_menuElegantActionPerformed

    private void comboBoxLugarBodaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxLugarBodaItemStateChanged
        // TODO add your handling code here:
        switch (comboBoxLugarBoda.getSelectedIndex()) {
            case 0:
                campoPrecioEvento.setText(String.valueOf(900));
                rBotonsalonHotel1.setText("Salón Aquamarina");
                rBotonsalonHotel2.setText("Salón Toledo");
                break;
            case 1:
                campoPrecioEvento.setText(String.valueOf(800));
                rBotonsalonHotel1.setText("Salón Azul");
                rBotonsalonHotel2.setText("Salón Verde");
                break;
            case 2:
                campoPrecioEvento.setText(String.valueOf(700));
                rBotonsalonHotel1.setText("Salón Madrid");
                rBotonsalonHotel2.setText("Salón Barcelona");
                break;
            default:
                campoPrecioEvento.setText(String.valueOf(0));
                rBotonsalonHotel1.setText("Salón...");
                rBotonsalonHotel2.setText("Salón...");
        }
    }//GEN-LAST:event_comboBoxLugarBodaItemStateChanged

    private void spinnerNinnosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerNinnosStateChanged
        // TODO add your handling code here:
        if ((int) spinnerNinnos.getValue() > 0) {
            cBoxParque.setVisible(true);
        }

        if ((int) spinnerAdultos.getValue() + (int) spinnerNinnos.getValue() >= 199) {
            JOptionPane.showMessageDialog(this, "Numero de asistentes maximo alcanzado");
            spinnerNinnos.setEnabled(false);
            spinnerAdultos.setEnabled(false);

        }
    }//GEN-LAST:event_spinnerNinnosStateChanged

    private void spinnerAdultosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerAdultosStateChanged
        // TODO add your handling code here:
        if ((int) spinnerAdultos.getValue() + (int) spinnerNinnos.getValue() >= 199) {
            JOptionPane.showMessageDialog(this, "Numero de asistentes maximo alcanzado");
            spinnerAdultos.setEnabled(false);
            spinnerNinnos.setEnabled(false);

        }
    }//GEN-LAST:event_spinnerAdultosStateChanged

    private void menuBasicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBasicActionPerformed
        // TODO add your handling code here:
        if (menuBasic.isSelected()) {
            campoPrecioEvento.setText(String.valueOf(
                    Integer.parseInt(campoPrecioEvento.getText())
                    + (int) spinnerAdultos.getValue() * 60
                    + (int) spinnerNinnos.getValue() * 30
            ));
        }

    }//GEN-LAST:event_menuBasicActionPerformed

    private void menuBasicStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_menuBasicStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_menuBasicStateChanged

    private void menuBasicItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_menuBasicItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_menuBasicItemStateChanged

    private void botonFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFinalizarActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "La reserva de: " + campoNombre.getText() + " tiene un precio de: " + campoPrecioEvento.getText()) == 0) {
            rBotonAceptadoSi.setSelected(true);
        } else {
            rBotonAceptadoNo.setSelected(true);
        }
        
    }//GEN-LAST:event_botonFinalizarActionPerformed

    private void spinnerCantidadAsistentesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerCantidadAsistentesStateChanged
        // TODO add your handling code here:
        if ((int)spinnerCantidadAsistentes.getValue() > 30 && (int)spinnerCantidadAsistentes.getValue() < 100 ) {
         cBoxTransporte.setVisible(true);
        }
    }//GEN-LAST:event_spinnerCantidadAsistentesStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameEvento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonFinalizar;
    private javax.swing.ButtonGroup buttonGroup1SalonHoteles;
    private javax.swing.ButtonGroup buttonGroup1TipoEvento;
    private javax.swing.ButtonGroup buttonGroup1TipoMenu;
    private javax.swing.ButtonGroup buttonGroupEventoAceptado;
    private javax.swing.JCheckBox cBoxAperitivo;
    private javax.swing.JCheckBox cBoxDisco;
    private javax.swing.JCheckBox cBoxOrquestaBoda;
    private javax.swing.JCheckBox cBoxParque;
    private javax.swing.JComboBox<String> cBoxSalon;
    private javax.swing.JCheckBox cBoxTransporte;
    private javax.swing.JCheckBox cBoxTransporteBoda;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoPrecioEvento;
    private javax.swing.JComboBox<String> comboBoxLugarBoda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton menuBasic;
    private javax.swing.JRadioButton menuElegant;
    private javax.swing.JPanel panelBoda;
    private javax.swing.JPanel panelCaracteristicasBoda;
    private javax.swing.JPanel panelCaracteristicasCongreso;
    private javax.swing.JPanel panelCongreso;
    private javax.swing.JRadioButton rBotonAceptadoNo;
    private javax.swing.JRadioButton rBotonAceptadoSi;
    private javax.swing.JRadioButton rBotonBoda;
    private javax.swing.JRadioButton rBotonCongreso;
    private javax.swing.JRadioButton rBotonsalonHotel1;
    private javax.swing.JRadioButton rBotonsalonHotel2;
    private javax.swing.JSpinner spinnerAdultos;
    private javax.swing.JSpinner spinnerCantidadAsistentes;
    private javax.swing.JSpinner spinnerNinnos;
    // End of variables declaration//GEN-END:variables
}
